studio-902580890:~/studio{master}$ npm run build
> nextn@0.1.0 build
> next build

   ▲ Next.js 15.2.3
   - Environments: .env.local, .env

   Creating an optimized production build ...
 ⚠ Compiled with warnings

./node_modules/@opentelemetry/sdk-node/build/src/TracerProviderWithEnvExporter.js
Module not found: Can't resolve '@opentelemetry/exporter-jaeger' in '/home/user/studio/node_modules/@opentelemetry/sdk-node/build/src'

Import trace for requested module:
./node_modules/@opentelemetry/sdk-node/build/src/TracerProviderWithEnvExporter.js
./node_modules/@opentelemetry/sdk-node/build/src/sdk.js
./node_modules/@opentelemetry/sdk-node/build/src/index.js
./node_modules/@genkit-ai/core/lib/tracing.js
./node_modules/@genkit-ai/ai/lib/chat.js
./node_modules/genkit/lib/common.js
./node_modules/genkit/lib/index.mjs
./src/ai/flows/summarize-announcement-flow.ts

./node_modules/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

Import trace for requested module:
./node_modules/handlebars/lib/index.js
./node_modules/dotprompt/dist/index.js
./node_modules/@genkit-ai/core/lib/registry.js
./node_modules/genkit/lib/registry.js
./node_modules/genkit/lib/genkit.js
./node_modules/genkit/lib/index.mjs
./src/ai/flows/summarize-announcement-flow.ts

./node_modules/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

Import trace for requested module:
./node_modules/handlebars/lib/index.js
./node_modules/dotprompt/dist/index.js
./node_modules/@genkit-ai/core/lib/registry.js
./node_modules/genkit/lib/registry.js
./node_modules/genkit/lib/genkit.js
./node_modules/genkit/lib/index.mjs
./src/ai/flows/summarize-announcement-flow.ts

./node_modules/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

Import trace for requested module:
./node_modules/handlebars/lib/index.js
./node_modules/dotprompt/dist/index.js
./node_modules/@genkit-ai/core/lib/registry.js
./node_modules/genkit/lib/registry.js
./node_modules/genkit/lib/genkit.js
./node_modules/genkit/lib/index.mjs
./src/ai/flows/summarize-announcement-flow.ts

 ✓ Compiled successfully
   Skipping validation of types
   Skipping linting
   Collecting page data  ..[Error [PageNotFoundError]: Cannot find module for page: /_not-found/page] {
  code: 'ENOENT'
}

> Build error occurred
[Error: Failed to collect page data for /_not-found] { type: 'Error' }